# Generated by Django 3.0.5 on 2020-04-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Baslik')),
                ('content', models.TextField(verbose_name='Icerik')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayinlama tarihi')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-pub_date', 'id'],
            },
        ),
    ]
